apiVersion: v1
kind: Pod
metadata:
  name: test-crashloop-pod
  namespace: default
  labels:
    app: test-crashloop
    kubesent-test: "true"
spec:
  containers:
  - name: failing-container
    image: busybox:latest
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "This pod will intentionally crash..."
        echo "Simulating application failure"
        exit 1  # Exit with error code to trigger CrashLoopBackOff
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
      requests:
        memory: "32Mi"
        cpu: "50m"
  restartPolicy: Always
