apiVersion: v1
kind: Pod
metadata:
  name: test-imagepull-pod
  namespace: default
  labels:
    app: test-imagepull
    kubesent-test: "true"
spec:
  containers:
  - name: nonexistent-image
    image: this-image-does-not-exist-12345:latest
    command: ["sleep", "3600"]
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
      requests:
        memory: "32Mi"
        cpu: "50m"
  restartPolicy: Always
