apiVersion: v1
kind: Pod
metadata:
  name: test-oomkilled-pod
  namespace: default
  labels:
    app: test-oomkilled
    kubesent-test: "true"
spec:
  containers:
  - name: memory-hog
    image: debian:bullseye-slim
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo "Starting memory hog process..."
        # Allocate memory in a loop to trigger OOMKilled
        while true; do
          dd if=/dev/zero of=/tmp/memory bs=1M count=50
          sleep 1
        done
    resources:
      limits:
        memory: "10Mi"  # This will be too small and trigger OOMKilled
      requests:
        memory: "10Mi"
  restartPolicy: Always
